//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Lusitania.Simuladores.WebSite.WSLUSNETConfig {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConfigSoap", Namespace="http://LUSITANIA/WSLUSNET/Framework/Aplicacoes/")]
    public partial class Config : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obterValorSettingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Config() {
            this.Url = global::Lusitania.Simuladores.WebSite.Properties.Settings.Default.Lusitania_Simuladores_WebSite_WSLUSNETConfig_Config;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obterValorSettingCompletedEventHandler obterValorSettingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://LUSITANIA/WSLUSNET/Framework/Aplicacoes/obterValorSetting", RequestNamespace="http://LUSITANIA/WSLUSNET/Framework/Aplicacoes/", ResponseNamespace="http://LUSITANIA/WSLUSNET/Framework/Aplicacoes/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obterValorSetting(short prmCompanhiaConexao, string prmContexto, string prmChave) {
            object[] results = this.Invoke("obterValorSetting", new object[] {
                        prmCompanhiaConexao,
                        prmContexto,
                        prmChave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obterValorSettingAsync(short prmCompanhiaConexao, string prmContexto, string prmChave) {
            this.obterValorSettingAsync(prmCompanhiaConexao, prmContexto, prmChave, null);
        }
        
        /// <remarks/>
        public void obterValorSettingAsync(short prmCompanhiaConexao, string prmContexto, string prmChave, object userState) {
            if ((this.obterValorSettingOperationCompleted == null)) {
                this.obterValorSettingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobterValorSettingOperationCompleted);
            }
            this.InvokeAsync("obterValorSetting", new object[] {
                        prmCompanhiaConexao,
                        prmContexto,
                        prmChave}, this.obterValorSettingOperationCompleted, userState);
        }
        
        private void OnobterValorSettingOperationCompleted(object arg) {
            if ((this.obterValorSettingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obterValorSettingCompleted(this, new obterValorSettingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obterValorSettingCompletedEventHandler(object sender, obterValorSettingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obterValorSettingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obterValorSettingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591