//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lusitania.Simuladores.WebSite.WsDocumentos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MlSegundaVia", Namespace="http://schemas.datacontract.org/2004/07/Lusitania.Model.Portais.PortalMediador.Do" +
        "cumentos")]
    [System.SerializableAttribute()]
    public partial class MlSegundaVia : Lusitania.Simuladores.WebSite.WsDocumentos.MlBaseOfMlSegundaViaYS0DbAY2 {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApoliceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataInicioReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTermoReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Imprime2ViaCVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Imprime2ViaReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ImprimeOriginalCVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ImprimeOriginalReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeSeguradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RamoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReciboField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apolice {
            get {
                return this.ApoliceField;
            }
            set {
                if ((object.ReferenceEquals(this.ApoliceField, value) != true)) {
                    this.ApoliceField = value;
                    this.RaisePropertyChanged("Apolice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataInicioRecibo {
            get {
                return this.DataInicioReciboField;
            }
            set {
                if ((object.ReferenceEquals(this.DataInicioReciboField, value) != true)) {
                    this.DataInicioReciboField = value;
                    this.RaisePropertyChanged("DataInicioRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTermoRecibo {
            get {
                return this.DataTermoReciboField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTermoReciboField, value) != true)) {
                    this.DataTermoReciboField = value;
                    this.RaisePropertyChanged("DataTermoRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Imprime2ViaCV {
            get {
                return this.Imprime2ViaCVField;
            }
            set {
                if ((this.Imprime2ViaCVField.Equals(value) != true)) {
                    this.Imprime2ViaCVField = value;
                    this.RaisePropertyChanged("Imprime2ViaCV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Imprime2ViaRecibo {
            get {
                return this.Imprime2ViaReciboField;
            }
            set {
                if ((this.Imprime2ViaReciboField.Equals(value) != true)) {
                    this.Imprime2ViaReciboField = value;
                    this.RaisePropertyChanged("Imprime2ViaRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ImprimeOriginalCV {
            get {
                return this.ImprimeOriginalCVField;
            }
            set {
                if ((this.ImprimeOriginalCVField.Equals(value) != true)) {
                    this.ImprimeOriginalCVField = value;
                    this.RaisePropertyChanged("ImprimeOriginalCV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ImprimeOriginalRecibo {
            get {
                return this.ImprimeOriginalReciboField;
            }
            set {
                if ((this.ImprimeOriginalReciboField.Equals(value) != true)) {
                    this.ImprimeOriginalReciboField = value;
                    this.RaisePropertyChanged("ImprimeOriginalRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeSegurado {
            get {
                return this.NomeSeguradoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeSeguradoField, value) != true)) {
                    this.NomeSeguradoField = value;
                    this.RaisePropertyChanged("NomeSegurado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCV {
            get {
                return this.NumeroCVField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCVField, value) != true)) {
                    this.NumeroCVField = value;
                    this.RaisePropertyChanged("NumeroCV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ramo {
            get {
                return this.RamoField;
            }
            set {
                if ((object.ReferenceEquals(this.RamoField, value) != true)) {
                    this.RamoField = value;
                    this.RaisePropertyChanged("Ramo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recibo {
            get {
                return this.ReciboField;
            }
            set {
                if ((object.ReferenceEquals(this.ReciboField, value) != true)) {
                    this.ReciboField = value;
                    this.RaisePropertyChanged("Recibo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MlBase", Namespace="http://schemas.datacontract.org/2004/07/Lusitania.LusnetBase")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Lusitania.Simuladores.WebSite.WsDocumentos.MlBaseOfMlSegundaViaYS0DbAY2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Lusitania.Simuladores.WebSite.WsDocumentos.MlSegundaVia))]
    public partial class MlBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MlBaseOfMlSegundaViaYS0DbAY2", Namespace="http://schemas.datacontract.org/2004/07/Lusitania.LusnetBase")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Lusitania.Simuladores.WebSite.WsDocumentos.MlSegundaVia))]
    public partial class MlBaseOfMlSegundaViaYS0DbAY2 : Lusitania.Simuladores.WebSite.WsDocumentos.MlBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsDocumentos.IWSDocumentos")]
    public interface IWSDocumentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDocumentos/obterListasSegundasVias", ReplyAction="http://tempuri.org/IWSDocumentos/obterListasSegundasViasResponse")]
        Lusitania.Simuladores.WebSite.WsDocumentos.MlSegundaVia[] obterListasSegundasVias(out string MensagemErro, out bool TemErro, short CompanhiaConexao, string Ramo, string Apolice, string NIF, string Recibo, string ApoliceExtracto, string ReciboExtracto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDocumentos/obterDocumentoPorWorkspace", ReplyAction="http://tempuri.org/IWSDocumentos/obterDocumentoPorWorkspaceResponse")]
        byte[] obterDocumentoPorWorkspace(out string Erro, short CompanhiaConexao, string Workspace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDocumentos/obterDocumentoApolicePorDocId", ReplyAction="http://tempuri.org/IWSDocumentos/obterDocumentoApolicePorDocIdResponse")]
        byte[] obterDocumentoApolicePorDocId(out string Erro, short CompanhiaConexao, string Ramo, string Apolice, string DocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDocumentos/obterDocumentoSinistroPorDocId", ReplyAction="http://tempuri.org/IWSDocumentos/obterDocumentoSinistroPorDocIdResponse")]
        byte[] obterDocumentoSinistroPorDocId(out string Erro, short CompanhiaConexao, string Ramo, string Modalidade, string Submodalidade, short Ano, string Sinistro, string DocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDocumentos/obterDocumentacaoProcesso", ReplyAction="http://tempuri.org/IWSDocumentos/obterDocumentacaoProcessoResponse")]
        byte[] obterDocumentacaoProcesso(string NomeModelo, string DirectorioFicheirosActivos, string DirectorioFicheirosRevogados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDocumentos/indexarDocumentoApolice", ReplyAction="http://tempuri.org/IWSDocumentos/indexarDocumentoApoliceResponse")]
        long indexarDocumentoApolice(out string MensagemErro, out bool TemErro, short CompanhiaConexao, string Ramo, string Apolice, string CentroCusto, System.DateTime DataDocumento, System.DateTime DataRegisto, string Descricao, string TipoDocumento, string NomeFicheiro, byte[] ConteudoFicheiro, int NumeroTentativas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDocumentos/RecuperaDocumentos", ReplyAction="http://tempuri.org/IWSDocumentos/RecuperaDocumentosResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="erro")]
        int RecuperaDocumentos(out string msg, short CompanhiaConexao, string Tipo_Doc, string Ramo, string Modalidade, string Submodalidade, string Apolice, short Ano, string Sinistro, int Pessoa, string DocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDocumentos/insereOutputDocUploadOnlineGuidDoc", ReplyAction="http://tempuri.org/IWSDocumentos/insereOutputDocUploadOnlineGuidDocResponse")]
        void insereOutputDocUploadOnlineGuidDoc(short companhiaConexao, string prmGuidDoc, decimal prmTipodoc, byte[] prmFicheiro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDocumentos/insereOutputDocUploadOnlineXML", ReplyAction="http://tempuri.org/IWSDocumentos/insereOutputDocUploadOnlineXMLResponse")]
        void insereOutputDocUploadOnlineXML(short companhiaConexao, string prmXmlDoc, decimal prmTipodoc, byte[] prmFicheiro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSDocumentosChannel : Lusitania.Simuladores.WebSite.WsDocumentos.IWSDocumentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDocumentosClient : System.ServiceModel.ClientBase<Lusitania.Simuladores.WebSite.WsDocumentos.IWSDocumentos>, Lusitania.Simuladores.WebSite.WsDocumentos.IWSDocumentos {
        
        public WSDocumentosClient() {
        }
        
        public WSDocumentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDocumentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDocumentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDocumentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Lusitania.Simuladores.WebSite.WsDocumentos.MlSegundaVia[] obterListasSegundasVias(out string MensagemErro, out bool TemErro, short CompanhiaConexao, string Ramo, string Apolice, string NIF, string Recibo, string ApoliceExtracto, string ReciboExtracto) {
            return base.Channel.obterListasSegundasVias(out MensagemErro, out TemErro, CompanhiaConexao, Ramo, Apolice, NIF, Recibo, ApoliceExtracto, ReciboExtracto);
        }
        
        public byte[] obterDocumentoPorWorkspace(out string Erro, short CompanhiaConexao, string Workspace) {
            return base.Channel.obterDocumentoPorWorkspace(out Erro, CompanhiaConexao, Workspace);
        }
        
        public byte[] obterDocumentoApolicePorDocId(out string Erro, short CompanhiaConexao, string Ramo, string Apolice, string DocId) {
            return base.Channel.obterDocumentoApolicePorDocId(out Erro, CompanhiaConexao, Ramo, Apolice, DocId);
        }
        
        public byte[] obterDocumentoSinistroPorDocId(out string Erro, short CompanhiaConexao, string Ramo, string Modalidade, string Submodalidade, short Ano, string Sinistro, string DocId) {
            return base.Channel.obterDocumentoSinistroPorDocId(out Erro, CompanhiaConexao, Ramo, Modalidade, Submodalidade, Ano, Sinistro, DocId);
        }
        
        public byte[] obterDocumentacaoProcesso(string NomeModelo, string DirectorioFicheirosActivos, string DirectorioFicheirosRevogados) {
            return base.Channel.obterDocumentacaoProcesso(NomeModelo, DirectorioFicheirosActivos, DirectorioFicheirosRevogados);
        }
        
        public long indexarDocumentoApolice(out string MensagemErro, out bool TemErro, short CompanhiaConexao, string Ramo, string Apolice, string CentroCusto, System.DateTime DataDocumento, System.DateTime DataRegisto, string Descricao, string TipoDocumento, string NomeFicheiro, byte[] ConteudoFicheiro, int NumeroTentativas) {
            return base.Channel.indexarDocumentoApolice(out MensagemErro, out TemErro, CompanhiaConexao, Ramo, Apolice, CentroCusto, DataDocumento, DataRegisto, Descricao, TipoDocumento, NomeFicheiro, ConteudoFicheiro, NumeroTentativas);
        }
        
        public int RecuperaDocumentos(out string msg, short CompanhiaConexao, string Tipo_Doc, string Ramo, string Modalidade, string Submodalidade, string Apolice, short Ano, string Sinistro, int Pessoa, string DocId) {
            return base.Channel.RecuperaDocumentos(out msg, CompanhiaConexao, Tipo_Doc, Ramo, Modalidade, Submodalidade, Apolice, Ano, Sinistro, Pessoa, DocId);
        }
        
        public void insereOutputDocUploadOnlineGuidDoc(short companhiaConexao, string prmGuidDoc, decimal prmTipodoc, byte[] prmFicheiro) {
            base.Channel.insereOutputDocUploadOnlineGuidDoc(companhiaConexao, prmGuidDoc, prmTipodoc, prmFicheiro);
        }
        
        public void insereOutputDocUploadOnlineXML(short companhiaConexao, string prmXmlDoc, decimal prmTipodoc, byte[] prmFicheiro) {
            base.Channel.insereOutputDocUploadOnlineXML(companhiaConexao, prmXmlDoc, prmTipodoc, prmFicheiro);
        }
    }
}
