//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lusitania.Simuladores.WebSite.WsPlanos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plano", Namespace="http://schemas.datacontract.org/2004/07/Lusitania.Model.Planos")]
    [System.SerializableAttribute()]
    public partial class Plano : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdesaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AncoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AngariadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CobradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPlanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataCriacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescontoComField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoPlanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElaboradoLogNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElaboradoTelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EscalaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MediadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroContratosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroImpressoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroRamosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PessoaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremioAnualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremioAnualDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProponenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessaoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TomadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adesao {
            get {
                return this.AdesaoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdesaoField, value) != true)) {
                    this.AdesaoField = value;
                    this.RaisePropertyChanged("Adesao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ancora {
            get {
                return this.AncoraField;
            }
            set {
                if ((object.ReferenceEquals(this.AncoraField, value) != true)) {
                    this.AncoraField = value;
                    this.RaisePropertyChanged("Ancora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Angariador {
            get {
                return this.AngariadorField;
            }
            set {
                if ((object.ReferenceEquals(this.AngariadorField, value) != true)) {
                    this.AngariadorField = value;
                    this.RaisePropertyChanged("Angariador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cobrador {
            get {
                return this.CobradorField;
            }
            set {
                if ((object.ReferenceEquals(this.CobradorField, value) != true)) {
                    this.CobradorField = value;
                    this.RaisePropertyChanged("Cobrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPlano {
            get {
                return this.CodigoPlanoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPlanoField, value) != true)) {
                    this.CodigoPlanoField = value;
                    this.RaisePropertyChanged("CodigoPlano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataCriacao {
            get {
                return this.DataCriacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataCriacaoField, value) != true)) {
                    this.DataCriacaoField = value;
                    this.RaisePropertyChanged("DataCriacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataInicio {
            get {
                return this.DataInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.DataInicioField, value) != true)) {
                    this.DataInicioField = value;
                    this.RaisePropertyChanged("DataInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataNascimentoField, value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescontoCom {
            get {
                return this.DescontoComField;
            }
            set {
                if ((object.ReferenceEquals(this.DescontoComField, value) != true)) {
                    this.DescontoComField = value;
                    this.RaisePropertyChanged("DescontoCom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoPlano {
            get {
                return this.DescricaoPlanoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoPlanoField, value) != true)) {
                    this.DescricaoPlanoField = value;
                    this.RaisePropertyChanged("DescricaoPlano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElaboradoLogNome {
            get {
                return this.ElaboradoLogNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.ElaboradoLogNomeField, value) != true)) {
                    this.ElaboradoLogNomeField = value;
                    this.RaisePropertyChanged("ElaboradoLogNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElaboradoTelefone {
            get {
                return this.ElaboradoTelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ElaboradoTelefoneField, value) != true)) {
                    this.ElaboradoTelefoneField = value;
                    this.RaisePropertyChanged("ElaboradoTelefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Escalao {
            get {
                return this.EscalaoField;
            }
            set {
                if ((object.ReferenceEquals(this.EscalaoField, value) != true)) {
                    this.EscalaoField = value;
                    this.RaisePropertyChanged("Escalao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mediador {
            get {
                return this.MediadorField;
            }
            set {
                if ((object.ReferenceEquals(this.MediadorField, value) != true)) {
                    this.MediadorField = value;
                    this.RaisePropertyChanged("Mediador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetodoPagamento {
            get {
                return this.MetodoPagamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoPagamentoField, value) != true)) {
                    this.MetodoPagamentoField = value;
                    this.RaisePropertyChanged("MetodoPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIB {
            get {
                return this.NIBField;
            }
            set {
                if ((object.ReferenceEquals(this.NIBField, value) != true)) {
                    this.NIBField = value;
                    this.RaisePropertyChanged("NIB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIF {
            get {
                return this.NIFField;
            }
            set {
                if ((object.ReferenceEquals(this.NIFField, value) != true)) {
                    this.NIFField = value;
                    this.RaisePropertyChanged("NIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroContratos {
            get {
                return this.NumeroContratosField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroContratosField, value) != true)) {
                    this.NumeroContratosField = value;
                    this.RaisePropertyChanged("NumeroContratos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroImpressoes {
            get {
                return this.NumeroImpressoesField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroImpressoesField, value) != true)) {
                    this.NumeroImpressoesField = value;
                    this.RaisePropertyChanged("NumeroImpressoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroRamos {
            get {
                return this.NumeroRamosField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroRamosField, value) != true)) {
                    this.NumeroRamosField = value;
                    this.RaisePropertyChanged("NumeroRamos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PessoaId {
            get {
                return this.PessoaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PessoaIdField, value) != true)) {
                    this.PessoaIdField = value;
                    this.RaisePropertyChanged("PessoaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanoId {
            get {
                return this.PlanoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanoIdField, value) != true)) {
                    this.PlanoIdField = value;
                    this.RaisePropertyChanged("PlanoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PremioAnual {
            get {
                return this.PremioAnualField;
            }
            set {
                if ((object.ReferenceEquals(this.PremioAnualField, value) != true)) {
                    this.PremioAnualField = value;
                    this.RaisePropertyChanged("PremioAnual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PremioAnualDesconto {
            get {
                return this.PremioAnualDescontoField;
            }
            set {
                if ((object.ReferenceEquals(this.PremioAnualDescontoField, value) != true)) {
                    this.PremioAnualDescontoField = value;
                    this.RaisePropertyChanged("PremioAnualDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proponente {
            get {
                return this.ProponenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ProponenteField, value) != true)) {
                    this.ProponenteField = value;
                    this.RaisePropertyChanged("Proponente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessaoId {
            get {
                return this.SessaoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessaoIdField, value) != true)) {
                    this.SessaoIdField = value;
                    this.RaisePropertyChanged("SessaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tomador {
            get {
                return this.TomadorField;
            }
            set {
                if ((object.ReferenceEquals(this.TomadorField, value) != true)) {
                    this.TomadorField = value;
                    this.RaisePropertyChanged("Tomador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagamento", Namespace="http://schemas.datacontract.org/2004/07/Lusitania.Model.Planos")]
    [System.SerializableAttribute()]
    public partial class Pagamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IBANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIBField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BIC {
            get {
                return this.BICField;
            }
            set {
                if ((object.ReferenceEquals(this.BICField, value) != true)) {
                    this.BICField = value;
                    this.RaisePropertyChanged("BIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBAN {
            get {
                return this.IBANField;
            }
            set {
                if ((object.ReferenceEquals(this.IBANField, value) != true)) {
                    this.IBANField = value;
                    this.RaisePropertyChanged("IBAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetodoPagamento {
            get {
                return this.MetodoPagamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoPagamentoField, value) != true)) {
                    this.MetodoPagamentoField = value;
                    this.RaisePropertyChanged("MetodoPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIB {
            get {
                return this.NIBField;
            }
            set {
                if ((object.ReferenceEquals(this.NIBField, value) != true)) {
                    this.NIBField = value;
                    this.RaisePropertyChanged("NIB");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaProv", Namespace="http://schemas.datacontract.org/2004/07/Lusitania.Model.Planos")]
    [System.SerializableAttribute()]
    public partial class PessoaProv : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pAoCuidado02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pCartaConducaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pCodigoPostal01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pCodigoPostal02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pDtCartaConducaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pDtNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pEMail01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pEstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pLocal01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pLocal02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pLocalidade01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pLocalidade02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pMoradaAndar01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pMoradaAndar02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pMoradaDesc01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pMoradaDesc02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pMoradaNumero01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pMoradaNumero02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pMoradaTipo01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pMoradaTipo02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pNacionalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPais01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPais02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPbiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPcodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPcontribField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPnomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPprofissField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPtipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pPtituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pSufixoPostal01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pSufixoPostal02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pTelefone01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pTelefone02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pTelemovelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pTelexFax01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pTelexFax02Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pAoCuidado02 {
            get {
                return this.pAoCuidado02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pAoCuidado02Field, value) != true)) {
                    this.pAoCuidado02Field = value;
                    this.RaisePropertyChanged("pAoCuidado02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pCartaConducao {
            get {
                return this.pCartaConducaoField;
            }
            set {
                if ((object.ReferenceEquals(this.pCartaConducaoField, value) != true)) {
                    this.pCartaConducaoField = value;
                    this.RaisePropertyChanged("pCartaConducao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pCodigoPostal01 {
            get {
                return this.pCodigoPostal01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pCodigoPostal01Field, value) != true)) {
                    this.pCodigoPostal01Field = value;
                    this.RaisePropertyChanged("pCodigoPostal01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pCodigoPostal02 {
            get {
                return this.pCodigoPostal02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pCodigoPostal02Field, value) != true)) {
                    this.pCodigoPostal02Field = value;
                    this.RaisePropertyChanged("pCodigoPostal02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pDtCartaConducao {
            get {
                return this.pDtCartaConducaoField;
            }
            set {
                if ((object.ReferenceEquals(this.pDtCartaConducaoField, value) != true)) {
                    this.pDtCartaConducaoField = value;
                    this.RaisePropertyChanged("pDtCartaConducao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pDtNascimento {
            get {
                return this.pDtNascimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.pDtNascimentoField, value) != true)) {
                    this.pDtNascimentoField = value;
                    this.RaisePropertyChanged("pDtNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pEMail01 {
            get {
                return this.pEMail01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pEMail01Field, value) != true)) {
                    this.pEMail01Field = value;
                    this.RaisePropertyChanged("pEMail01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pEstadoCivil {
            get {
                return this.pEstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.pEstadoCivilField, value) != true)) {
                    this.pEstadoCivilField = value;
                    this.RaisePropertyChanged("pEstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pLocal01 {
            get {
                return this.pLocal01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pLocal01Field, value) != true)) {
                    this.pLocal01Field = value;
                    this.RaisePropertyChanged("pLocal01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pLocal02 {
            get {
                return this.pLocal02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pLocal02Field, value) != true)) {
                    this.pLocal02Field = value;
                    this.RaisePropertyChanged("pLocal02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pLocalidade01 {
            get {
                return this.pLocalidade01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pLocalidade01Field, value) != true)) {
                    this.pLocalidade01Field = value;
                    this.RaisePropertyChanged("pLocalidade01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pLocalidade02 {
            get {
                return this.pLocalidade02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pLocalidade02Field, value) != true)) {
                    this.pLocalidade02Field = value;
                    this.RaisePropertyChanged("pLocalidade02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pMoradaAndar01 {
            get {
                return this.pMoradaAndar01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pMoradaAndar01Field, value) != true)) {
                    this.pMoradaAndar01Field = value;
                    this.RaisePropertyChanged("pMoradaAndar01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pMoradaAndar02 {
            get {
                return this.pMoradaAndar02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pMoradaAndar02Field, value) != true)) {
                    this.pMoradaAndar02Field = value;
                    this.RaisePropertyChanged("pMoradaAndar02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pMoradaDesc01 {
            get {
                return this.pMoradaDesc01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pMoradaDesc01Field, value) != true)) {
                    this.pMoradaDesc01Field = value;
                    this.RaisePropertyChanged("pMoradaDesc01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pMoradaDesc02 {
            get {
                return this.pMoradaDesc02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pMoradaDesc02Field, value) != true)) {
                    this.pMoradaDesc02Field = value;
                    this.RaisePropertyChanged("pMoradaDesc02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pMoradaNumero01 {
            get {
                return this.pMoradaNumero01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pMoradaNumero01Field, value) != true)) {
                    this.pMoradaNumero01Field = value;
                    this.RaisePropertyChanged("pMoradaNumero01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pMoradaNumero02 {
            get {
                return this.pMoradaNumero02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pMoradaNumero02Field, value) != true)) {
                    this.pMoradaNumero02Field = value;
                    this.RaisePropertyChanged("pMoradaNumero02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pMoradaTipo01 {
            get {
                return this.pMoradaTipo01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pMoradaTipo01Field, value) != true)) {
                    this.pMoradaTipo01Field = value;
                    this.RaisePropertyChanged("pMoradaTipo01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pMoradaTipo02 {
            get {
                return this.pMoradaTipo02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pMoradaTipo02Field, value) != true)) {
                    this.pMoradaTipo02Field = value;
                    this.RaisePropertyChanged("pMoradaTipo02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pNacionalidade {
            get {
                return this.pNacionalidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.pNacionalidadeField, value) != true)) {
                    this.pNacionalidadeField = value;
                    this.RaisePropertyChanged("pNacionalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPais01 {
            get {
                return this.pPais01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pPais01Field, value) != true)) {
                    this.pPais01Field = value;
                    this.RaisePropertyChanged("pPais01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPais02 {
            get {
                return this.pPais02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pPais02Field, value) != true)) {
                    this.pPais02Field = value;
                    this.RaisePropertyChanged("pPais02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPbi {
            get {
                return this.pPbiField;
            }
            set {
                if ((object.ReferenceEquals(this.pPbiField, value) != true)) {
                    this.pPbiField = value;
                    this.RaisePropertyChanged("pPbi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPcodigo {
            get {
                return this.pPcodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.pPcodigoField, value) != true)) {
                    this.pPcodigoField = value;
                    this.RaisePropertyChanged("pPcodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPcontrib {
            get {
                return this.pPcontribField;
            }
            set {
                if ((object.ReferenceEquals(this.pPcontribField, value) != true)) {
                    this.pPcontribField = value;
                    this.RaisePropertyChanged("pPcontrib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPnome {
            get {
                return this.pPnomeField;
            }
            set {
                if ((object.ReferenceEquals(this.pPnomeField, value) != true)) {
                    this.pPnomeField = value;
                    this.RaisePropertyChanged("pPnome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPprofiss {
            get {
                return this.pPprofissField;
            }
            set {
                if ((object.ReferenceEquals(this.pPprofissField, value) != true)) {
                    this.pPprofissField = value;
                    this.RaisePropertyChanged("pPprofiss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPtipo {
            get {
                return this.pPtipoField;
            }
            set {
                if ((object.ReferenceEquals(this.pPtipoField, value) != true)) {
                    this.pPtipoField = value;
                    this.RaisePropertyChanged("pPtipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pPtitulo {
            get {
                return this.pPtituloField;
            }
            set {
                if ((object.ReferenceEquals(this.pPtituloField, value) != true)) {
                    this.pPtituloField = value;
                    this.RaisePropertyChanged("pPtitulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pSufixoPostal01 {
            get {
                return this.pSufixoPostal01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pSufixoPostal01Field, value) != true)) {
                    this.pSufixoPostal01Field = value;
                    this.RaisePropertyChanged("pSufixoPostal01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pSufixoPostal02 {
            get {
                return this.pSufixoPostal02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pSufixoPostal02Field, value) != true)) {
                    this.pSufixoPostal02Field = value;
                    this.RaisePropertyChanged("pSufixoPostal02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pTelefone01 {
            get {
                return this.pTelefone01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pTelefone01Field, value) != true)) {
                    this.pTelefone01Field = value;
                    this.RaisePropertyChanged("pTelefone01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pTelefone02 {
            get {
                return this.pTelefone02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pTelefone02Field, value) != true)) {
                    this.pTelefone02Field = value;
                    this.RaisePropertyChanged("pTelefone02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pTelemovel {
            get {
                return this.pTelemovelField;
            }
            set {
                if ((object.ReferenceEquals(this.pTelemovelField, value) != true)) {
                    this.pTelemovelField = value;
                    this.RaisePropertyChanged("pTelemovel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pTelexFax01 {
            get {
                return this.pTelexFax01Field;
            }
            set {
                if ((object.ReferenceEquals(this.pTelexFax01Field, value) != true)) {
                    this.pTelexFax01Field = value;
                    this.RaisePropertyChanged("pTelexFax01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pTelexFax02 {
            get {
                return this.pTelexFax02Field;
            }
            set {
                if ((object.ReferenceEquals(this.pTelexFax02Field, value) != true)) {
                    this.pTelexFax02Field = value;
                    this.RaisePropertyChanged("pTelexFax02");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractList", Namespace="http://schemas.datacontract.org/2004/07/ModelPlanos")]
    [System.SerializableAttribute()]
    public partial class ContractList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Lusitania.Simuladores.WebSite.WsPlanos.Contract[] ContractField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Lusitania.Simuladores.WebSite.WsPlanos.Contract[] Contract {
            get {
                return this.ContractField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractField, value) != true)) {
                    this.ContractField = value;
                    this.RaisePropertyChanged("Contract");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/ModelPlanos")]
    [System.SerializableAttribute()]
    public partial class Contract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Lusitania.Simuladores.WebSite.WsPlanos.ParamList ParamListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Lusitania.Simuladores.WebSite.WsPlanos.ParamList ParamList {
            get {
                return this.ParamListField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamListField, value) != true)) {
                    this.ParamListField = value;
                    this.RaisePropertyChanged("ParamList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamList", Namespace="http://schemas.datacontract.org/2004/07/ModelPlanos")]
    [System.SerializableAttribute()]
    public partial class ParamList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Lusitania.Simuladores.WebSite.WsPlanos.Param[] ParamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Lusitania.Simuladores.WebSite.WsPlanos.Param[] Param {
            get {
                return this.ParamField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamField, value) != true)) {
                    this.ParamField = value;
                    this.RaisePropertyChanged("Param");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Param", Namespace="http://schemas.datacontract.org/2004/07/ModelPlanos")]
    [System.SerializableAttribute()]
    public partial class Param : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string directionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                if ((object.ReferenceEquals(this.directionField, value) != true)) {
                    this.directionField = value;
                    this.RaisePropertyChanged("direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                if ((object.ReferenceEquals(this.valorField, value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsPlanos.IWSPlanos")]
    public interface IWSPlanos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPlanos/ObtemProxVencimentoPlanos", ReplyAction="http://tempuri.org/IWSPlanos/ObtemProxVencimentoPlanosResponse")]
        string ObtemProxVencimentoPlanos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPlanos/GetProxVencimentoPlanos2", ReplyAction="http://tempuri.org/IWSPlanos/GetProxVencimentoPlanos2Response")]
        string GetProxVencimentoPlanos2(System.DateTime data_inicio, string cod_plano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPlanos/ObtemDadosPlano", ReplyAction="http://tempuri.org/IWSPlanos/ObtemDadosPlanoResponse")]
        Lusitania.Simuladores.WebSite.WsPlanos.Plano ObtemDadosPlano(string plan_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPlanos/ObtemDadosPagamento", ReplyAction="http://tempuri.org/IWSPlanos/ObtemDadosPagamentoResponse")]
        Lusitania.Simuladores.WebSite.WsPlanos.Pagamento ObtemDadosPagamento(string plan_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPlanos/ObtemURLPlano", ReplyAction="http://tempuri.org/IWSPlanos/ObtemURLPlanoResponse")]
        string ObtemURLPlano(out string planCode, out string planDesc, string planID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPlanos/InsereDadosPagamento", ReplyAction="http://tempuri.org/IWSPlanos/InsereDadosPagamentoResponse")]
        bool InsereDadosPagamento(out string error_code, out string error_description, string plan_id, string metodo_pagamento, string nib);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPlanos/Saber_PessoaProv", ReplyAction="http://tempuri.org/IWSPlanos/Saber_PessoaProvResponse")]
        Lusitania.Simuladores.WebSite.WsPlanos.PessoaProv[] Saber_PessoaProv(string PlanID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPlanos/SaveContract", ReplyAction="http://tempuri.org/IWSPlanos/SaveContractResponse")]
        Lusitania.Simuladores.WebSite.WsPlanos.ContractList SaveContract(out string cod_error, out string desc_error, Lusitania.Simuladores.WebSite.WsPlanos.ContractList listaContratos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPlanos/PreSelectCommercialAccount", ReplyAction="http://tempuri.org/IWSPlanos/PreSelectCommercialAccountResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mediator")]
        string PreSelectCommercialAccount(out string collector, string planID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSPlanosChannel : Lusitania.Simuladores.WebSite.WsPlanos.IWSPlanos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPlanosClient : System.ServiceModel.ClientBase<Lusitania.Simuladores.WebSite.WsPlanos.IWSPlanos>, Lusitania.Simuladores.WebSite.WsPlanos.IWSPlanos {
        
        public WSPlanosClient() {
        }
        
        public WSPlanosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPlanosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPlanosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPlanosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtemProxVencimentoPlanos() {
            return base.Channel.ObtemProxVencimentoPlanos();
        }
        
        public string GetProxVencimentoPlanos2(System.DateTime data_inicio, string cod_plano) {
            return base.Channel.GetProxVencimentoPlanos2(data_inicio, cod_plano);
        }
        
        public Lusitania.Simuladores.WebSite.WsPlanos.Plano ObtemDadosPlano(string plan_id) {
            return base.Channel.ObtemDadosPlano(plan_id);
        }
        
        public Lusitania.Simuladores.WebSite.WsPlanos.Pagamento ObtemDadosPagamento(string plan_id) {
            return base.Channel.ObtemDadosPagamento(plan_id);
        }
        
        public string ObtemURLPlano(out string planCode, out string planDesc, string planID) {
            return base.Channel.ObtemURLPlano(out planCode, out planDesc, planID);
        }
        
        public bool InsereDadosPagamento(out string error_code, out string error_description, string plan_id, string metodo_pagamento, string nib) {
            return base.Channel.InsereDadosPagamento(out error_code, out error_description, plan_id, metodo_pagamento, nib);
        }
        
        public Lusitania.Simuladores.WebSite.WsPlanos.PessoaProv[] Saber_PessoaProv(string PlanID) {
            return base.Channel.Saber_PessoaProv(PlanID);
        }
        
        public Lusitania.Simuladores.WebSite.WsPlanos.ContractList SaveContract(out string cod_error, out string desc_error, Lusitania.Simuladores.WebSite.WsPlanos.ContractList listaContratos) {
            return base.Channel.SaveContract(out cod_error, out desc_error, listaContratos);
        }
        
        public string PreSelectCommercialAccount(out string collector, string planID) {
            return base.Channel.PreSelectCommercialAccount(out collector, planID);
        }
    }
}
