//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lusitania.Simuladores.WebSite {
    
    
    public partial class Home {
        
        /// <summary>
        /// hDebugLoggedUserControlUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel hDebugLoggedUserControlUpdatePanel;
        
        /// <summary>
        /// hDebugLoggedUserControlPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel hDebugLoggedUserControlPanel;
        
        /// <summary>
        /// hDebugLoggedUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Controls_DebugLoggedUserControl hDebugLoggedUserControl;
    }
}
