//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bicicletas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bicicletas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Bicicletas", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início não pode ser posterior a {0}.
        /// </summary>
        internal static string ErrorMessageMaximumDateBegin {
            get {
                return ResourceManager.GetString("ErrorMessageMaximumDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início não pode ser anterior a {0}.
        /// </summary>
        internal static string ErrorMessageMinimumDateBegin {
            get {
                return ResourceManager.GetString("ErrorMessageMinimumDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;b&gt;Note o seguinte:&lt;/b&gt;&lt;li&gt;&lt;b&gt;Oferta de Seguro de Vida&lt;/b&gt;&lt;br /&gt;Para uma protecção completa, a Lusitania oferece-lhe, caso estejam reunidas as condições necessárias para a subscrição/aceitação deste risco pela Lusitania Vida, Companhia de Seguros, SA., um seguro de vida que garante um capital de € xxxx em caso de Morte do Tomador de Seguro, tendo a Pessoa Segura como beneficiário;&lt;/li&gt;&lt;li&gt;A(s) Pessoa(s) Segura(s) terão de ter até 17 anos de idade na data de adesão, permanecendo no máximo até aos 18 anos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lblWarning {
            get {
                return ResourceManager.GetString("lblWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Início.
        /// </summary>
        internal static string ltlDateBegin {
            get {
                return ResourceManager.GetString("ltlDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Início:.
        /// </summary>
        internal static string ltlDateBegin1 {
            get {
                return ResourceManager.GetString("ltlDateBegin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de Pessoas Seguras.
        /// </summary>
        internal static string ltlNumberOfChildren {
            get {
                return ResourceManager.GetString("ltlNumberOfChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de Pessoas Seguras:.
        /// </summary>
        internal static string ltlNumberOfChildren1 {
            get {
                return ResourceManager.GetString("ltlNumberOfChildren1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulações Acidentes Pessoais.
        /// </summary>
        internal static string ManagementHeaderText {
            get {
                return ResourceManager.GetString("ManagementHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa de Simulações Acidentes Pessoais.
        /// </summary>
        internal static string ManagementPageTitle {
            get {
                return ResourceManager.GetString("ManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção: A cobertura {0} só está disponível para crianças a partir dos 6 anos!.
        /// </summary>
        internal static string _018 {
            get {
                return ResourceManager.GetString("018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção: A cobertura {0} só está disponível para crianças a partir dos 6 anos!.
        /// </summary>
        internal static string _020 {
            get {
                return ResourceManager.GetString("020", resourceCulture);
            }
        }
    }
}
