//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hunter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hunter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Hunter", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Nasc..
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raça.
        /// </summary>
        internal static string Breed {
            get {
                return ResourceManager.GetString("Breed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cães a declarar.
        /// </summary>
        internal static string DeclareDogs {
            get {
                return ResourceManager.GetString("DeclareDogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para cães legalmente classificados como potencialmente perigosos ou perigosos, é obrigatório o seguro de Responsabilidade Civil para Cães, nos termos da legislação em vigor aplicável..
        /// </summary>
        internal static string DeclareDogsInformation {
            get {
                return ResourceManager.GetString("DeclareDogsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armas a declarar.
        /// </summary>
        internal static string DeclareGuns {
            get {
                return ResourceManager.GetString("DeclareGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identif. Electrónica.
        /// </summary>
        internal static string EID {
            get {
                return ResourceManager.GetString("EID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} tem caracteres inválidos!.
        /// </summary>
        internal static string ErrorMsgInvalidChars {
            get {
                return ResourceManager.GetString("ErrorMsgInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não é válido!.
        /// </summary>
        internal static string ErrorMsgInvalidValue {
            get {
                return ResourceManager.GetString("ErrorMsgInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início não pode ser posterior a {0}.
        /// </summary>
        internal static string ErrorMsgMaximumDateBegin {
            get {
                return ResourceManager.GetString("ErrorMsgMaximumDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de cães não pode ser superior a {0}.
        /// </summary>
        internal static string ErrorMsgMaximumNumberOfDogs {
            get {
                return ResourceManager.GetString("ErrorMsgMaximumNumberOfDogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de armas não pode ser superior a {0}.
        /// </summary>
        internal static string ErrorMsgMaximumNumberOfGuns {
            get {
                return ResourceManager.GetString("ErrorMsgMaximumNumberOfGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início não pode ser anterior a {0}.
        /// </summary>
        internal static string ErrorMsgMinimumDateBegin {
            get {
                return ResourceManager.GetString("ErrorMsgMinimumDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de cães não pode ser inferior a {0}.
        /// </summary>
        internal static string ErrorMsgMinimumNumberOfDogs {
            get {
                return ResourceManager.GetString("ErrorMsgMinimumNumberOfDogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de armas não pode ser inferior a {0}.
        /// </summary>
        internal static string ErrorMsgMinimumNumberOfGuns {
            get {
                return ResourceManager.GetString("ErrorMsgMinimumNumberOfGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Início:.
        /// </summary>
        internal static string ltlDateBegin {
            get {
                return ResourceManager.GetString("ltlDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de Cães:.
        /// </summary>
        internal static string ltlNumberOfDogs {
            get {
                return ResourceManager.GetString("ltlNumberOfDogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de Armas:.
        /// </summary>
        internal static string ltlNumberOfGuns {
            get {
                return ResourceManager.GetString("ltlNumberOfGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulações Plano do Caçador.
        /// </summary>
        internal static string ManagementHeaderText {
            get {
                return ResourceManager.GetString("ManagementHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa de Simulações Plano do Caçador.
        /// </summary>
        internal static string ManagementPageTitle {
            get {
                return ResourceManager.GetString("ManagementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Campos obrigatórios.
        /// </summary>
        internal static string MandatoryLegend {
            get {
                return ResourceManager.GetString("MandatoryLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório estar preenchido!.
        /// </summary>
        internal static string MandatoryMsg {
            get {
                return ResourceManager.GetString("MandatoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string MaxLengthDate {
            get {
                return ResourceManager.GetString("MaxLengthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string MaxLengthSpec {
            get {
                return ResourceManager.GetString("MaxLengthSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [\sa-zA-Zà-ÿÀ-Ý0-9&apos;\-]*.
        /// </summary>
        internal static string RegExpInvalidChars1 {
            get {
                return ResourceManager.GetString("RegExpInvalidChars1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [\sa-zA-Zà-ÿÀ-Ý0-9&apos;\-]*.
        /// </summary>
        internal static string RegExpInvalidChars2 {
            get {
                return ResourceManager.GetString("RegExpInvalidChars2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de Série.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Prémio Total inclui {0} cão adicional, ao preço unitário de {1}..
        /// </summary>
        internal static string WarningMsgDogs1 {
            get {
                return ResourceManager.GetString("WarningMsgDogs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Prémio Total inclui {0} cães adicionais, ao preço unitário de {1}..
        /// </summary>
        internal static string WarningMsgDogsN {
            get {
                return ResourceManager.GetString("WarningMsgDogsN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Prémio Total inclui {0} arma adicional, ao preço unitário de {1}..
        /// </summary>
        internal static string WarningMsgGuns1 {
            get {
                return ResourceManager.GetString("WarningMsgGuns1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Prémio Total inclui {0} armas adicionais, ao preço unitário de {1}..
        /// </summary>
        internal static string WarningMsgGunsN {
            get {
                return ResourceManager.GetString("WarningMsgGunsN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Módulo I não prevê a inclusão de Armas e/ou Cães..
        /// </summary>
        internal static string WarningMsgProductModuloI {
            get {
                return ResourceManager.GetString("WarningMsgProductModuloI", resourceCulture);
            }
        }
    }
}
