//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiários por Morte.
        /// </summary>
        internal static string BeneficiariesByDeath {
            get {
                return ResourceManager.GetString("BeneficiariesByDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Pessoas Seguras de idade até 14 anos, a cobertura Morte ou Invalidez Permanente apenas garante o risco de Invalidez Permanente.&lt;br&gt;As Pessoas Seguras terão de ter até 65 anos de idade na data de adesão..
        /// </summary>
        internal static string BicicletasSimDisclaimer {
            get {
                return ResourceManager.GetString("BicicletasSimDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro Bicicletas.pdf.
        /// </summary>
        internal static string BicicletasSimulator_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("BicicletasSimulator_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro Protecção Criança.pdf.
        /// </summary>
        internal static string ChildrenProtectionSimulator_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("ChildrenProtectionSimulator_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro de Condomínio.pdf.
        /// </summary>
        internal static string Condominium_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("Condominium_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cobertura Edíficio é obrigatória..
        /// </summary>
        internal static string Condominium_SelectAtLeastOneScope {
            get {
                return ResourceManager.GetString("Condominium_SelectAtLeastOneScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Contrato foi emitido com sucesso..
        /// </summary>
        internal static string ContractSavedOK {
            get {
                return ResourceManager.GetString("ContractSavedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data da Carta de Condução é anterior à Data de Maioridade..
        /// </summary>
        internal static string DriverLicenseDateIsTooSoon {
            get {
                return ResourceManager.GetString("DriverLicenseDateIsTooSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível obter o BIC automáticamente. Por favor efectue a pesquisa..
        /// </summary>
        internal static string ErroPesquisaBIC {
            get {
                return ResourceManager.GetString("ErroPesquisaBIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início não pode ser posterior a {0}.
        /// </summary>
        internal static string ErrorMessageMaximumDateBegin {
            get {
                return ResourceManager.GetString("ErrorMessageMaximumDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de início não pode ser anterior a {0}.
        /// </summary>
        internal static string ErrorMessageMinimumDateBegin {
            get {
                return ResourceManager.GetString("ErrorMessageMinimumDateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgiu um erro na submissão, por favor tente novamente!.
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha os dados do tomador para iniciar o Plano Família..
        /// </summary>
        internal static string FamilyPlanSimulator_HolderInfoNeeded {
            get {
                return ResourceManager.GetString("FamilyPlanSimulator_HolderInfoNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os contratos foram gravados com sucesso..
        /// </summary>
        internal static string FamilyPlan_AllContractsSavedSuccessfully {
            get {
                return ResourceManager.GetString("FamilyPlan_AllContractsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível adicionar mais nenhum seguro automóvel..
        /// </summary>
        internal static string FamilyPlan_CannotAddMoreCarSimulations {
            get {
                return ResourceManager.GetString("FamilyPlan_CannotAddMoreCarSimulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível adicionar mais nenhum seguro de saúde..
        /// </summary>
        internal static string FamilyPlan_CannotAddMoreHealthSimulations {
            get {
                return ResourceManager.GetString("FamilyPlan_CannotAddMoreHealthSimulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme todas as acções antes de emitir os contratos..
        /// </summary>
        internal static string FamilyPlan_ConfirmAllActionsBeforeContract {
            get {
                return ResourceManager.GetString("FamilyPlan_ConfirmAllActionsBeforeContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível inicializar o Plano de Família..
        /// </summary>
        internal static string FamilyPlan_CouldNotCreateFamilyPlan {
            get {
                return ResourceManager.GetString("FamilyPlan_CouldNotCreateFamilyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione pelo menos uma apólice antes de adicioná-las ao Plano..
        /// </summary>
        internal static string FamilyPlan_NoPolicyIsSelectedToAdd {
            get {
                return ResourceManager.GetString("FamilyPlan_NoPolicyIsSelectedToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Plano Família.pdf.
        /// </summary>
        internal static string FamilyPlan_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("FamilyPlan_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A apólice seleccionada foi adicionada ao plano com sucesso..
        /// </summary>
        internal static string FamilyPlan_ThePolicyWasAddedToThePlan {
            get {
                return ResourceManager.GetString("FamilyPlan_ThePolicyWasAddedToThePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados do Tomador de Seguro foram gravados com sucesso.
        ///Atenção, o Tomador de Seguro já tem {0} Planos Família Lusitania.
        ///Pode prosseguir a Simulação até à Folha de Adesão.
        ///Para efectivar o contrato contacte o seu Técnico Comercial..
        /// </summary>
        internal static string FamilyPlan_UserHas_X_PreviousPlans {
            get {
                return ResourceManager.GetString("FamilyPlan_UserHas_X_PreviousPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As {0} apólices seleccionadas foram adicionadas ao Plano com sucesso..
        /// </summary>
        internal static string FamilyPlan_X_PolicesWereAddedToThePlan_FormatString {
            get {
                return ResourceManager.GetString("FamilyPlan_X_PolicesWereAddedToThePlan_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação RENDA FAMILIAR Lusitania.
        /// </summary>
        internal static string FamilyRent_QuotationSubjectText {
            get {
                return ResourceManager.GetString("FamilyRent_QuotationSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione uma opção para o Tomador ou para o Cônjuge..
        /// </summary>
        internal static string FamilyRent_SelectAtLeastHolderOrSpouse {
            get {
                return ResourceManager.GetString("FamilyRent_SelectAtLeastHolderOrSpouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique se o Titular tem Herdeiros Legais..
        /// </summary>
        internal static string FamilyRent_SelectIfHolderHasLegalHeirs {
            get {
                return ResourceManager.GetString("FamilyRent_SelectIfHolderHasLegalHeirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique se o Cônjuge tem Herdeiros Legais..
        /// </summary>
        internal static string FamilyRent_SelectIfSpouseHasLegalHeirs {
            get {
                return ResourceManager.GetString("FamilyRent_SelectIfSpouseHasLegalHeirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O NIF do Cônjuge é igual ao do Tomador..
        /// </summary>
        internal static string FamilyRent_SpouseNifIsEqualToHolderNif {
            get {
                return ResourceManager.GetString("FamilyRent_SpouseNifIsEqualToHolderNif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O NIF indicado não é válido..
        /// </summary>
        internal static string FiscalNumberIsNotValid {
            get {
                return ResourceManager.GetString("FiscalNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string Gender_Female_Abreviation {
            get {
                return ResourceManager.GetString("Gender_Female_Abreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string Gender_Male_Abreviation {
            get {
                return ResourceManager.GetString("Gender_Male_Abreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentaria.
        /// </summary>
        internal static string HealthProduct_Dentaria {
            get {
                return ResourceManager.GetString("HealthProduct_Dentaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livre.
        /// </summary>
        internal static string HealthProduct_Livre {
            get {
                return ResourceManager.GetString("HealthProduct_Livre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleno.
        /// </summary>
        internal static string HealthProduct_Pleno {
            get {
                return ResourceManager.GetString("HealthProduct_Pleno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior.
        /// </summary>
        internal static string HealthProduct_Senior {
            get {
                return ResourceManager.GetString("HealthProduct_Senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filho.
        /// </summary>
        internal static string HealthSimulator_Kid {
            get {
                return ResourceManager.GetString("HealthSimulator_Kid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma Pessoa.
        /// </summary>
        internal static string HealthSimulator_NumberOfPeople_One {
            get {
                return ResourceManager.GetString("HealthSimulator_NumberOfPeople_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Pessoas.
        /// </summary>
        internal static string HealthSimulator_NumberOfPeople_ThreeOrMore_FormatString {
            get {
                return ResourceManager.GetString("HealthSimulator_NumberOfPeople_ThreeOrMore_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duas Pessoas.
        /// </summary>
        internal static string HealthSimulator_NumberOfPeople_Two {
            get {
                return ResourceManager.GetString("HealthSimulator_NumberOfPeople_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro de Saúde.pdf.
        /// </summary>
        internal static string HealthSimulator_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("HealthSimulator_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cônjuge.
        /// </summary>
        internal static string HealthSimulator_Spouse {
            get {
                return ResourceManager.GetString("HealthSimulator_Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular.
        /// </summary>
        internal static string Health_FamilyMember_Holder {
            get {
                return ResourceManager.GetString("Health_FamilyMember_Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filho.
        /// </summary>
        internal static string Health_FamilyMember_Kid {
            get {
                return ResourceManager.GetString("Health_FamilyMember_Kid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outro.
        /// </summary>
        internal static string Health_FamilyMember_Other {
            get {
                return ResourceManager.GetString("Health_FamilyMember_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cônjuge.
        /// </summary>
        internal static string Health_FamilyMember_Spouse {
            get {
                return ResourceManager.GetString("Health_FamilyMember_Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações do Plano.
        /// </summary>
        internal static string Health_ShowPlanInfo {
            get {
                return ResourceManager.GetString("Health_ShowPlanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herdeiros Legais do Titular ?.
        /// </summary>
        internal static string HolderHasHeirs {
            get {
                return ResourceManager.GetString("HolderHasHeirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação Multiriscos Habitação Lusitania.
        /// </summary>
        internal static string HomeSimulator_QuotationEmailSubject_FormatString {
            get {
                return ResourceManager.GetString("HomeSimulator_QuotationEmailSubject_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro Multiriscos Habitação.pdf.
        /// </summary>
        internal static string Home_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("Home_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor total de {0} não é válido..
        /// </summary>
        internal static string Home_TotalValueOf_X_IsNotValid {
            get {
                return ResourceManager.GetString("Home_TotalValueOf_X_IsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro de Empregada Doméstica.pdf.
        /// </summary>
        internal static string Housemaid_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("Housemaid_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro Caçador.pdf.
        /// </summary>
        internal static string HunterSimulator_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("HunterSimulator_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação CAÇADOR Lusitania.
        /// </summary>
        internal static string Hunter_QuotationSubjectText {
            get {
                return ResourceManager.GetString("Hunter_QuotationSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro de Trabalhador Independente.pdf.
        /// </summary>
        internal static string IndependantWorker_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("IndependantWorker_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação TRABALHADOR INDEPENDENTE Lusitania.
        /// </summary>
        internal static string IndependantWorker_QuotationSubjectText {
            get {
                return ResourceManager.GetString("IndependantWorker_QuotationSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível efectuar o seguro com débitos por liquidar. Por favor, contacte o seu técnico comercial..
        /// </summary>
        internal static string LeisureCraftProposal_CannotDoNewInsuranceWithUnpaidOldInsurance {
            get {
                return ResourceManager.GetString("LeisureCraftProposal_CannotDoNewInsuranceWithUnpaidOldInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para iniciar a proposta, deve indicar o NIF do Tomador..
        /// </summary>
        internal static string LeisureCraftSimulator_NifIsRequiredForProposal {
            get {
                return ResourceManager.GetString("LeisureCraftSimulator_NifIsRequiredForProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro de Embarcações de Recreio.pdf.
        /// </summary>
        internal static string LeisureCraft_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("LeisureCraft_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação EMBARCAÇÕES DE RECREIO Lusitania.
        /// </summary>
        internal static string LeisureCraft_QuotationSubjectText {
            get {
                return ResourceManager.GetString("LeisureCraft_QuotationSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string MaxLengthCompany {
            get {
                return ResourceManager.GetString("MaxLengthCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string MaxLengthHeir {
            get {
                return ResourceManager.GetString("MaxLengthHeir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar o Cache.
        /// </summary>
        internal static string Menu_ClearCache {
            get {
                return ResourceManager.GetString("Menu_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cache foi limpo..
        /// </summary>
        internal static string Menu_TheCacheWasCleared {
            get {
                return ResourceManager.GetString("Menu_TheCacheWasCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registo está associado a um Plano Familia pelo que não pode passar a contrato por este ecrã.
        /// </summary>
        internal static string NoContract_FamilyPlan {
            get {
                return ResourceManager.GetString("NoContract_FamilyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já passaram mais de 30 dias da data de simulação pelo que este registo não pode passar a contrato.
        /// </summary>
        internal static string NoContract_Over30days {
            get {
                return ResourceManager.GetString("NoContract_Over30days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.A..
        /// </summary>
        internal static string NotAvailable_ShortHand {
            get {
                return ResourceManager.GetString("NotAvailable_ShortHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro de Renda Familiar.pdf.
        /// </summary>
        internal static string PersonalAccidents_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("PersonalAccidents_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione um Cliente.
        /// </summary>
        internal static string PersonInfo_SelectAnEnterpriseClient {
            get {
                return ResourceManager.GetString("PersonInfo_SelectAnEnterpriseClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione um Cliente.
        /// </summary>
        internal static string PersonInfo_SelectPersonClient {
            get {
                return ResourceManager.GetString("PersonInfo_SelectPersonClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada informação relativa à sua pesquisa..
        /// </summary>
        internal static string PersonSearch_NoPersonFound {
            get {
                return ResourceManager.GetString("PersonSearch_NoPersonFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A proposta foi alterada. Terá de gravá-la para passar a contrato..
        /// </summary>
        internal static string ProposalHasChangedMustSaveItAgain {
            get {
                return ResourceManager.GetString("ProposalHasChangedMustSaveItAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A proposta foi alterada, terá de guardá-la antes de prosseguir..
        /// </summary>
        internal static string ProposalIsDirty {
            get {
                return ResourceManager.GetString("ProposalIsDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Proposta foi gravada com sucesso..
        /// </summary>
        internal static string Proposal_ProposalCreatedOK {
            get {
                return ResourceManager.GetString("Proposal_ProposalCreatedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A proposta terá de ser enviada para aprovação.
        /// </summary>
        internal static string Proposal_ProposalSentForAcceptance {
            get {
                return ResourceManager.GetString("Proposal_ProposalSentForAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os seus dados pessoais ainda não estão preenchidos.&lt;br&gt;Deseja imprimir mesmo assim?.
        /// </summary>
        internal static string QuestaoImpCotacao {
            get {
                return ResourceManager.GetString("QuestaoImpCotacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Cotação foi enviada com sucesso..
        /// </summary>
        internal static string QuotationSentSuccessfully {
            get {
                return ResourceManager.GetString("QuotationSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Riscos
        ///Habitação.
        /// </summary>
        internal static string Receipt_Title_Home {
            get {
                return ResourceManager.GetString("Receipt_Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empregada
        ///Doméstica.
        /// </summary>
        internal static string Receipt_Title_Housemaid {
            get {
                return ResourceManager.GetString("Receipt_Title_Housemaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embarcações
        ///Recreio.
        /// </summary>
        internal static string Receipt_Title_LeisureCraft {
            get {
                return ResourceManager.GetString("Receipt_Title_LeisureCraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIKEINSURANCEQUOTATION.
        /// </summary>
        internal static string RecordSetQuotation {
            get {
                return ResourceManager.GetString("RecordSetQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento temporariamente indisponível. Por favor tente mais tarde..
        /// </summary>
        internal static string SapIsNOK {
            get {
                return ResourceManager.GetString("SapIsNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione o Parentesco.
        /// </summary>
        internal static string SelectKinText {
            get {
                return ResourceManager.GetString("SelectKinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###TO###,
        ///
        ///###FROM-NAME### [###FROM-EMAIL###] enviou-lhe a simulação de seguro em anexo.
        ///
        ///###MESSAGE###.
        /// </summary>
        internal static string SendQuotation_Body_FormatString {
            get {
                return ResourceManager.GetString("SendQuotation_Body_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lusitania.
        /// </summary>
        internal static string SendQuotation_From_Name {
            get {
                return ResourceManager.GetString("SendQuotation_From_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dúvidas ou Sugestões - Simulador {0}.
        /// </summary>
        internal static string SendSuggestion_Subject_FormatString {
            get {
                return ResourceManager.GetString("SendSuggestion_Subject_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua mensagem foi enviada com sucesso. Obrigado pela sua participação..
        /// </summary>
        internal static string SendSuggestion_Success {
            get {
                return ResourceManager.GetString("SendSuggestion_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envie-nos as suas dúvidas ou sugestões sobre o simulador {0}:.
        /// </summary>
        internal static string SendSuggestion_Title_FormatString {
            get {
                return ResourceManager.GetString("SendSuggestion_Title_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os seus dados pessoais ainda não estão preenchidos. Deseja imprimir mesmo assim?.
        /// </summary>
        internal static string Simulator_ConfirmPrint {
            get {
                return ResourceManager.GetString("Simulator_ConfirmPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para iniciar a proposta, deve indicar o NIF do Tomador..
        /// </summary>
        internal static string Simulator_NifIsRequiredForProposal {
            get {
                return ResourceManager.GetString("Simulator_NifIsRequiredForProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os seus dados pessoais ainda não estão preenchidos. Deseja continuar mesmo assim?.
        /// </summary>
        internal static string TravelSimulator_ConfirmPrint {
            get {
                return ResourceManager.GetString("TravelSimulator_ConfirmPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dias.
        /// </summary>
        internal static string TravelSimulator_DurationFormatString_Plural {
            get {
                return ResourceManager.GetString("TravelSimulator_DurationFormatString_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dia.
        /// </summary>
        internal static string TravelSimulator_DurationFormatString_Singular {
            get {
                return ResourceManager.GetString("TravelSimulator_DurationFormatString_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem Bagagem.
        /// </summary>
        internal static string TravelSimulator_NoLuggage {
            get {
                return ResourceManager.GetString("TravelSimulator_NoLuggage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobertura.
        /// </summary>
        internal static string TravelSimulator_PlanInfo_Coverage {
            get {
                return ResourceManager.GetString("TravelSimulator_PlanInfo_Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Seguro de Viagem.pdf.
        /// </summary>
        internal static string TravelSimulator_QuotationAttachmentNameForPdf {
            get {
                return ResourceManager.GetString("TravelSimulator_QuotationAttachmentNameForPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobertura.
        /// </summary>
        internal static string TravelSimulator_TravelAssistanceInfo_CoverageNameHeader {
            get {
                return ResourceManager.GetString("TravelSimulator_TravelAssistanceInfo_CoverageNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string TravelSimulator_TravelAssistanceInfo_NoValue {
            get {
                return ResourceManager.GetString("TravelSimulator_TravelAssistanceInfo_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilimitado.
        /// </summary>
        internal static string TravelSimulator_TravelAssistanceInfo_UnlimitedValue {
            get {
                return ResourceManager.GetString("TravelSimulator_TravelAssistanceInfo_UnlimitedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluída.
        /// </summary>
        internal static string TravelSimulator_TravelAssistance_Included {
            get {
                return ResourceManager.GetString("TravelSimulator_TravelAssistance_Included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Incluída.
        /// </summary>
        internal static string TravelSimulator_TravelAssistance_NotIncluded {
            get {
                return ResourceManager.GetString("TravelSimulator_TravelAssistance_NotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Voyage_NoValue {
            get {
                return ResourceManager.GetString("Voyage_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilimitado.
        /// </summary>
        internal static string Voyage_Unlimited {
            get {
                return ResourceManager.GetString("Voyage_Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível efectuar o seguro com débitos por liquidar. Por favor, contacte o seu técnico comercial..
        /// </summary>
        internal static string WorkAccidentsProposal_CannotDoNewInsuranceWithUnpaidOldInsurance {
            get {
                return ResourceManager.GetString("WorkAccidentsProposal_CannotDoNewInsuranceWithUnpaidOldInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cotacao_rc.xdp.
        /// </summary>
        internal static string XDPQuotation {
            get {
                return ResourceManager.GetString("XDPQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
